name: prokemn_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  google_fonts: ^6.2.1
  get_it: ^9.2.1
  go_router: ^15.1.3
  riverpod: ^3.2.1
  freezed: ^3.2.5
  freezed_annotation: ^3.1.0
  riverpod_annotation: ^4.0.2
  flutter_localization: ^0.3.3
  flutter_riverpod: ^3.2.1
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  http: ^1.2.2
  url_launcher: ^6.2.5
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  build_runner: ^2.4.15
  riverpod_generator: ^4.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/image/

